### ISSUE TITLE
Any way to override light and dark themes seprately and switch between them?

### ISSUE THREAD

**Issue by arjunkathuria** [petergardfjall/emacs-immaterial-theme#2]
Hi, Cool theme @petergardfjall !

i am trying to use the light variant during day time and the dark variant during night time.

but overriding say `backgroud-primary` overrides it in BOTH light and dark variants.

i am looking for some thing so i can configure separate settings for the two. i am not sure i understand what roles to `background-light` or `primary-light` play since they do not refer to the light variant's background and primary colors. hope i could get my issue across.

quite simply i think i may be missing something here.

**Comment by petergardfjall** [comment]
Hi, thanks for the feedback!

Much of the code dates back to a time when there was only a dark variant of the theme. Some parts, like the color override customization as well as the `primary-dark`/`primary-light` naming reflects that.

With the recent commit https://github.com/petergardfjall/emacs-immaterial-theme/releases/tag/v0.8.0 I've tried to correct that. The `immaterial-color-override-alist` is now more flexible, capable of changing colors for either variant of the theme. The README goes into more detail but here is an example: 

```emacs-lisp
(setq immaterial-color-override-alist
  '(("background-primary" . ((dark  . "#000000") (light . "#eeffdd")))
    ("background-on"      . ((dark  . "#003300") (light . "#ddffaa")))
    ;; override 'primary' only for dark theme
    ("primary"            . ((dark  . "#80cbc4")))
    ;; override 'warning' only for light theme
    ("warning"            . ((light . "#ed4079")))))
```

Also the accent colors  (`primary`,`secondary`,`tertiary`) now support two variants `hi` and `lo` (contrast, with respect to the background color) instead of `dark` and `light`.

Feel free to try it out.

**Comment by arjunkathuria** [comment]
Hi!

This is wonderful @petergardfjall , i played around a bit & this works _exactly_ as i wanted 🥇 

Thanks a lot for taking a look into this and a super quick turnaround 💯
